# Generated by Django 5.0.6 on 2024-07-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_alter_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
